// Generated by gencpp from file controls/encoder_msg.msg
// DO NOT EDIT!


#ifndef CONTROLS_MESSAGE_ENCODER_MSG_H
#define CONTROLS_MESSAGE_ENCODER_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controls
{
template <class ContainerAllocator>
struct encoder_msg_
{
  typedef encoder_msg_<ContainerAllocator> Type;

  encoder_msg_()
    : left_vel(0.0)
    , right_vel(0.0)  {
    }
  encoder_msg_(const ContainerAllocator& _alloc)
    : left_vel(0.0)
    , right_vel(0.0)  {
    }



   typedef float _left_vel_type;
  _left_vel_type left_vel;

   typedef float _right_vel_type;
  _right_vel_type right_vel;




  typedef boost::shared_ptr< ::controls::encoder_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controls::encoder_msg_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_msg_

typedef ::controls::encoder_msg_<std::allocator<void> > encoder_msg;

typedef boost::shared_ptr< ::controls::encoder_msg > encoder_msgPtr;
typedef boost::shared_ptr< ::controls::encoder_msg const> encoder_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controls::encoder_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controls::encoder_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace controls

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/debian/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'controls': ['/home/debian/controls_on_beagle_bone/main_controls/src/controls/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::controls::encoder_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controls::encoder_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controls::encoder_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controls::encoder_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controls::encoder_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controls::encoder_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controls::encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74ad8f7ea4d888606e4f41069cec47ff";
  }

  static const char* value(const ::controls::encoder_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74ad8f7ea4d88860ULL;
  static const uint64_t static_value2 = 0x6e4f41069cec47ffULL;
};

template<class ContainerAllocator>
struct DataType< ::controls::encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controls/encoder_msg";
  }

  static const char* value(const ::controls::encoder_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controls::encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left_vel	\n\
float32 right_vel\n\
";
  }

  static const char* value(const ::controls::encoder_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controls::encoder_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_vel);
      stream.next(m.right_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct encoder_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controls::encoder_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controls::encoder_msg_<ContainerAllocator>& v)
  {
    s << indent << "left_vel: ";
    Printer<float>::stream(s, indent + "  ", v.left_vel);
    s << indent << "right_vel: ";
    Printer<float>::stream(s, indent + "  ", v.right_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLS_MESSAGE_ENCODER_MSG_H
