FILE(MAKE_DIRECTORY "/home/agv/catkin_ws/devel/share/decision_making_examples/graphs" )
FILE(GLOB_RECURSE FOR_DEL /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/* )
#message("delete files from /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/ : ${FOR_DEL}")
if( FOR_DEL )
	FILE(REMOVE ${FOR_DEL})
endif()
execute_process(COMMAND /home/agv/catkin_ws/devel/lib/decision_making_parser/decision_making_parser -pe -xml -dot -src "/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples" -dst "/home/agv/catkin_ws/devel/share/decision_making_examples/graphs" -f "/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples/src/fsm/Roomba.cpp:/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples/src/fsm/Turnstile.cpp:/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples/src/fsm/Wandering.cpp:/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples/src/hsm/ScxmlHierarchyExample.cpp:/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples/src/tao/TaoExample.cpp:/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples/src/tao/TaoIncrement.cpp:/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples/src/hsm/Mission.cpp:" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/ /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.scxml /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.btxml  /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.taoxml)
message("   -- Created XML files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.scxml /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.btxml /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.taoxml)
execute_process(COMMAND "python" /home/agv/catkin_ws/devel/lib/decision_making_parser/decision_making_xml_parser.py -i "/home/agv/catkin_ws/src/eklavya-2015/decision_making/decision_making_examples" "/home/agv/catkin_ws/devel/share/decision_making_examples/graphs" "${CREATED_FILES_ABS}" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/ /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.dot /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.xot)
message("   -- Created DOT files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.dot)
foreach( f ${CREATED_FILES_ABS} )
	execute_process(COMMAND "dot" -q1 -Tgif -o${f}.gif  ${f} RESULT_VARIABLE rv)
endforeach()
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/ /home/agv/catkin_ws/devel/share/decision_making_examples/graphs/*.gif)
message("   -- Created GIF files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
