controller_frequency: 10.0
TrajectoryPlannerROS:
  max_vel_x: 2.24
  min_vel_x: 0.45
  max_rotational_vel: 3.44
  min_in_place_vel_th: 0
  acc_lim_theta: 0.1
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  pdist_scale: 0.8
  gdist_scale: 0.9
  occdist_scale: 0.5
  escape_reset_theta: 0

  holonomic_robot: false
  yaw_goal_tolerance: 0.8
  xy_goal_tolerance: 0.6
  goal_distance_bias: 0.4
  path_distance_bias: 0.0
  sim_time: 0.5
  heading_scoring: true
  heading_lookahead: 0.7
  oscillation_reset_dist: 0.25
  backup_vel: 0.0

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

