controller_frequency: 10.0
TrajectoryPlannerROS:
  max_vel_x: 1.00
  min_vel_x: 0.10
  max_rotational_vel: 3.1
  min_in_place_rotational_vel: 1.0
  acc_lim_theta: 2.0
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  holonomic_robot: false
  yaw_goal_tolerance: 0.8
  xy_goal_tolerance: 0.6
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 5.0
  heading_lookahead: 0.5
  oscillation_reset_dist: 0.25

  vx_samples: 6
  vy_samples: 6
  vtheta_samples: 20
  dwa: true

