FILE(MAKE_DIRECTORY "/home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs" )
FILE(GLOB_RECURSE FOR_DEL /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/* )
#message("delete files from /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/ : ${FOR_DEL}")
if( FOR_DEL )
	FILE(REMOVE ${FOR_DEL})
endif()
execute_process(COMMAND /home/aranya/catkin_ws/devel/lib/decision_making_parser/decision_making_parser -pe -xml -dot -src "/home/aranya/catkin_ws/src/eklavya-2015/navigation/high_level_planner_igvc" -dst "/home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs" -f "/home/aranya/catkin_ws/src/eklavya-2015/navigation/high_level_planner_igvc/src/fsm_high_level_planner_igvc.cpp:" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/ /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.scxml /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.btxml  /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.taoxml)
message("   -- Created XML files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.scxml /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.btxml /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.taoxml)
execute_process(COMMAND "python" /home/aranya/catkin_ws/devel/lib/decision_making_parser/decision_making_xml_parser.py -i "/home/aranya/catkin_ws/src/eklavya-2015/navigation/high_level_planner_igvc" "/home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs" "${CREATED_FILES_ABS}" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/ /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.dot /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.xot)
message("   -- Created DOT files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.dot)
foreach( f ${CREATED_FILES_ABS} )
	execute_process(COMMAND "dot" -q1 -Tgif -o${f}.gif  ${f} RESULT_VARIABLE rv)
endforeach()
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/ /home/aranya/catkin_ws/devel/share/high_level_planner_igvc/graphs/*.gif)
message("   -- Created GIF files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
